version: '3.9'
#which service is going to run docker file
services:
  app:
    build:
      context: .  #root directory (denotes where we have to build the docker file in current directory)
      args:
        - DEV=true

    ports:
      - "8000:8000" #helps to access the network when we want to connect to our server
    volumes:
      - ./app:/app #mapping directories from our system into the docker container(for updates so that changes reflect to project in real time)
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:
 



